
CREATE DATABASE `ims` /*!40100 COLLATE 'utf8mb4_bin' */;
USE `ims`;

# 創建IP白名單表記錄
CREATE TABLE `t_ip_whitelist` (
	`id` INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主鍵ID',
	`ip_addr` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'IP地址',
	`is_enable` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否激活可用 0-否 1-是',
	`comments` CHAR(50) NOT NULL DEFAULT '' COMMENT '備註信息',
	`create_at` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '創建時間戳',
	`update_at` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新時間戳',
	`delete_at` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '刪除時間戳'
) ENGINE=MYISAM AUTO_INCREMENT=0 COMMENT='IP白名單控制訪問權限';